import type { AssemblerBackend, AssemblyRequest, AssemblyResult } from '../../src/features/toolchain/model';
import { buildAssemblyProject } from '../../src/features/toolchain/projectAssemblyBuild';
import type { InspectorProject } from '../../src/features/project/model';

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

class FakeBackend implements AssemblerBackend {
  readonly id = 'fake-nasm';
  readonly name = 'Fake NASM';
  request: AssemblyRequest | null = null;

  async assemble(request: AssemblyRequest): Promise<AssemblyResult> {
    this.request = request;
    return {
      success: true,
      artifact: {
        path: '/work/build/program',
        kind: 'elf-executable',
        bytes: Uint8Array.from([0x7f, 0x45, 0x4c, 0x46]),
        generatedBy: 'fixture'
      },
      generatedArtifacts: [],
      diagnostics: [],
      stdout: 'assembled\n',
      stderr: ''
    };
  }
}

const project: InspectorProject = {
  schemaVersion: 1,
  id: 'project-1',
  name: 'fixture',
  createdAt: 1,
  updatedAt: 1,
  files: [
    {
      id: 'main', path: 'src/main.asm', name: 'main.asm', kind: 'text', language: 'asm',
      text: 'global _start\n_start:\n  ret\n', size: 31, updatedAt: 1
    },
    {
      id: 'helper', path: 'src/helper.asm', name: 'helper.asm', kind: 'text', language: 'asm',
      text: 'global helper\nhelper:\n  ret\n', size: 29, updatedAt: 1
    },
    {
      id: 'notes', path: 'notes.txt', name: 'notes.txt', kind: 'text', language: 'text',
      text: 'ignore me', size: 9, updatedAt: 1
    }
  ]
};

const backend = new FakeBackend();
const single = await buildAssemblyProject(project, backend, { sourceFileIds: ['main'] });
assert(single.assembly.success, 'single-source project build should succeed');
assert(backend.request?.sources.length === 1, 'single-source selection should only send the active ASM source');
assert(single.generatedFile?.path === 'build/main', `unexpected generated project path: ${single.generatedFile?.path}`);
assert(single.generatedFile?.id === 'generated:project-1:build/main', 'generated project id should be stable across rebuilds');
assert(single.generatedFile?.kind === 'binary' && single.generatedFile.language === 'binary', 'generated artifact must enter the project as a normal binary file');
assert(single.generatedFile?.generated?.backendId === 'fake-nasm', 'generated artifact should retain backend provenance');
assert(single.generatedFile?.generated?.sourceFileIds.join(',') === 'main', 'generated artifact should retain exact source provenance');
assert(single.generatedFile?.bytes && new Uint8Array(single.generatedFile.bytes)[0] === 0x7f, 'generated bytes must be copied into an authoritative ArrayBuffer');

const allBackend = new FakeBackend();
const multi = await buildAssemblyProject(project, allBackend);
assert(multi.assembly.success, 'default project build should include all ASM source files');
assert(allBackend.request?.sources.map((source) => source.path).join(',') === 'src/main.asm,src/helper.asm', 'default build should exclude non-ASM project files');
assert(multi.generatedFile?.path === 'build/program', 'multi-source default output should use build/program');
assert(multi.generatedFile?.generated?.sourceFileIds.join(',') === 'main,helper', 'multi-source provenance should preserve build order');

const invalidBackend = new FakeBackend();
const invalid = await buildAssemblyProject(project, invalidBackend, { sourceFileIds: ['notes'] });
assert(!invalid.assembly.success && invalid.generatedFile === null, 'non-ASM source selection must fail before invoking the backend');
assert(invalidBackend.request === null, 'invalid source selection must not invoke the assembler backend');

console.log('project assembly build smoke: PASS (source selection -> backend -> stable generated binary ProjectFile)');
